### ISSUE TITLE
How to trust a self-signed certificate?

### ISSUE THREAD

**Issue by tobykurien** [baasbox/Android-SDK#23]
I'd like to connect from my Android app to an SSL server using a self-signed certificate. How do I go about doing this? If I follow the documented code, I get this exception:

```
08-07 11:12:15.496: E/AndroidRuntime(4540): Caused by: com.baasbox.android.BaasIOException: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
08-07 11:12:15.496: E/AndroidRuntime(4540):     at com.baasbox.android.HttpUrlConnectionClient.execute(HttpUrlConnectionClient.java:181)
08-07 11:12:15.496: E/AndroidRuntime(4540):     at com.baasbox.android.NetworkTask.asyncCall(NetworkTask.java:151)
08-07 11:12:15.496: E/AndroidRuntime(4540):     at com.baasbox.android.impl.Task.execute(Task.java:189)
08-07 11:12:15.496: E/AndroidRuntime(4540):     at com.baasbox.android.impl.Dispatcher$Worker.run(Dispatcher.java:170)
08-07 11:12:15.496: E/AndroidRuntime(4540): Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
08-07 11:12:15.496: E/AndroidRuntime(4540):     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:409)
08-07 11:12:15.496: E/AndroidRuntime(4540):     at com.android.okhttp.Connection.upgradeToTls(Connection.java:146)
08-07 11:12:15.496: E/AndroidRuntime(4540):     at com.android.okhttp.Connection.connect(Connection.java:107)
08-07 11:12:15.496: E/AndroidRuntime(4540):     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:294)
08-07 11:12:15.496: E/AndroidRuntime(4540):     at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:255)
08-07 11:12:15.496: E/AndroidRuntime(4540):     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:206)
08-07 11:12:15.496: E/AndroidRuntime(4540):     at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345)
08-07 11:12:15.496: E/AndroidRuntime(4540):     at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:89)
08-07 11:12:15.496: E/AndroidRuntime(4540):     at com.android.okhttp.internal.http.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:161)
08-07 11:12:15.496: E/AndroidRuntime(4540):     at com.baasbox.android.HttpUrlConnectionClient.execute(HttpUrlConnectionClient.java:157)
08-07 11:12:15.496: E/AndroidRuntime(4540):     ... 3 more
08-07 11:12:15.496: E/AndroidRuntime(4540): Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
08-07 11:12:15.496: E/AndroidRuntime(4540):     at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:282)
08-07 11:12:15.496: E/AndroidRuntime(4540):     at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:202)
08-07 11:12:15.496: E/AndroidRuntime(4540):     at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:611)
08-07 11:12:15.496: E/AndroidRuntime(4540):     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
08-07 11:12:15.496: E/AndroidRuntime(4540):     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:405)
08-07 11:12:15.496: E/AndroidRuntime(4540):     ... 12 more
08-07 11:12:15.496: E/AndroidRuntime(4540): Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
08-07 11:12:15.496: E/AndroidRuntime(4540):     ... 17 more
```

**Comment by Ranafugaz** [comment]
Hello,

The correct way is fork the library, add Baasbox as a module dependency and modify the following methods inside the class HttpUrlConnectionClient.class like the following:

(The following example uses both self-signed client and server certificate.

```
private HostnameVerifier mHostVerifier = new HostnameVerifier() {
        @Override
        public boolean verify(String hostname, SSLSession session) {
            //HostnameVerifier hv =
            //        HttpsURLConnection.getDefaultHostnameVerifier();
            //return hv.verify("domain.com", session);
            return hostname.equals("myip");
        }
    };
```

```
@Override
    public void init(Context context,BaasBox.Config config){
        this.config = config;
        if (config.useHttps){
            mSSLSocketFactory = createSocketFactory(context);
        }
        disableReuseConnectionIfNecessary(config.useHttps);
        enableHttpCacheIfAvailable(context,HTTP_CACHE_SIZE);
    }
```

```
    private static SSLSocketFactory createSocketFactory(Context context){
        InputStream in = null;
        try {
            SSLContext sslContext = null;
            try {

                //Here we add the server.crt or the ca.crt (Certificate authority) that we will trust
                CertificateFactory cf = CertificateFactory.getInstance("X.509");
                InputStream caInput = context.getAssets().open("server.crt");
                Certificate ca;
                ca = cf.generateCertificate(caInput);
                sslContext = SSLContext.getInstance("TLS");
                String keyStoreType = "PKCS12";
                KeyStore keyStore = KeyStore.getInstance(keyStoreType);
                keyStore.setCertificateEntry("ca", ca);

                //Here we add the client certificate to send to the server
                String clientCertPassword = "mypassword";
                keyStore.load(context.getAssets().open("client.p12"), clientCertPassword.toCharArray());

                KeyManagerFactory kmf = KeyManagerFactory.getInstance("X509");
                kmf.init(keyStore, clientCertPassword.toCharArray());
                KeyManager[] keyManagers = kmf.getKeyManagers();

                String tmfAlgorithm = TrustManagerFactory.getDefaultAlgorithm();
                TrustManagerFactory tmf = TrustManagerFactory.getInstance(tmfAlgorithm);
                tmf.init(keyStore);

                //If we don't use client certificate just use:
                //sslContext.init(null, tmf.getTrustManagers(), null);
                sslContext.init(keyManagers, tmf.getTrustManagers(), null);
            } catch (KeyManagementException | IOException | CertificateException | NoSuchAlgorithmException | KeyStoreException | UnrecoverableKeyException e) {
                e.printStackTrace();
            }

            return sslContext.getSocketFactory();
        } catch (Exception e) {
            throw new BaasRuntimeException(e);
        }finally {
            if(in != null){
                try {
                    in.close();
                } catch (IOException e) {
                    // swallow
                }
            }
        }
    }
```

```

private HttpURLConnection openConnection(String urlString) throws BaasIOException, IOException {
        URL url = null;
        try {
            url = new URL(urlString);
        } catch (MalformedURLException e) {
            throw new BaasIOException("Error while parsing url " + urlString, e);
        }
        HttpsURLConnection connection = (HttpsURLConnection) url.openConnection();
        if (config.useHttps) {
            connection.setSSLSocketFactory(mSSLSocketFactory);
            connection.setHostnameVerifier(mHostVerifier);
        }
        connection.setConnectTimeout(config.httpConnectionTimeout);
        connection.setReadTimeout(config.httpSocketTimeout);
        connection.setInstanceFollowRedirects(true);
        connection.setDoInput(true);

        return connection;
    }
```
