### ISSUE TITLE
getting file stream throws NullPointerException [Android]

### ISSUE THREAD

**Issue by seza443** [baasbox/Android-SDK#39]
Hello,

I've a problem similar to [this closed issue](https://github.com/baasbox/Android-SDK/issues/17)
When trying to retrieve a stream from a file, Baasbox throws the following error:

    java.lang.RuntimeException: java.lang.NullPointerException
            at com.baasbox.android.ExceptionHandler$1.onError(ExceptionHandler.java:33)
            at com.baasbox.android.impl.Dispatcher$Worker.run(Dispatcher.java:174)
    Caused by: java.lang.NullPointerException
            at com.baasbox.android.StreamBody.finishStream(StreamBody.java:40)
            at com.baasbox.android.AsyncStream.onOk(AsyncStream.java:115)
            at com.baasbox.android.NetworkTask.parseResponse(NetworkTask.java:60)
            at com.baasbox.android.NetworkTask.asyncCall(NetworkTask.java:152)
            at com.baasbox.android.impl.Task.execute(Task.java:189)
            at com.baasbox.android.impl.Dispatcher$Worker.run(Dispatcher.java:170)

To retrieve the file I use [the same code as the documentation](http://www.baasbox.com/documentation/?java#retrieve-a-file)

```Java
files.get(i).stream(new BaasHandler<BaasFile>() {
    @Override
    public void handle(BaasResult<BaasFile> res) {
        if (res.isSuccess()) {
            byte[] data = res.value().getData();

           //do things with data

            Log.d("LOG", "File received");
        } else {
            Log.e("LOG", "Error while streaming", res.error());
        }
    }
});
```

**Comment by seza443** [comment]
Sorry, I was using Baasbox 0.9.1
It works fine with 0.9.2
